"""empty message

Revision ID: 0e30b713a97b
Revises: 
Create Date: 2025-01-13 20:53:37.392849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e30b713a97b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_list_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_list_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statelocation', sa.String(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('statelocation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_list_states')
    op.drop_table('check_list_data')
    # ### end Alembic commands ###
